version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - ./backend/.env:/app/.env:ro
    command: npm run dev
    restart: unless-stopped
    networks:
      - invoice-network-dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - ./frontend/.env:/app/.env:ro
    command: npm run dev
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - invoice-network-dev

networks:
  invoice-network-dev:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:
